### ISSUE TITLE
PI Control

### ISSUE THREAD

**Issue by JorgeLopezCasillas** [marlen6457/Proyecto_Integrador_DSE_2019#26]
This is the PI control that controls the duty cycle for DC Motor.

- [ ] Reading pulses RPM.

- [ ] Calculate the constants Kp and Ti.

- [ ] Function to set the new duty cycle value (closed loop control system)
